g = [['calm','comfort','quiet','serene','mellow','chill out','calm down','calming','chillout','comforting','content','cool down','mellow music','mellow rock','peace of mind','quietness','relaxation','serenity','solace','soothe','soothing','still','tranquil','tranquility','tranquility']
,['sad','sadness','unhappy','melancholic','melancholy','feeling sad,slightly sad','sad song']
,['happy','happiness','happy songs','happy music','glad','mood: happy']
,['romantic','romantic music']
,['upbeat','gleeful','high spirits','zest','enthusiastic','buoyancy','elation','mood: upbeat']
,['depressed','blue','dark','depressive','dreary','gloom','darkness','depress','depression','depressing','gloomy']
,['anger','angry','choleric','fury','outraged','rage','angry music']
,['grief','heartbreak','mournful','sorrow','sorry','doleful','heartache','heartbreaking','heartsick','lachrymose','mourning','plaintive','regret','sorrowful']
,['dreamy']
,['cheerful','cheer up','festive','jolly','jovial','merry','cheer','cheering','cheery','get happy','rejoice','songs that are cheerful','sunny']
,['brooding','contemplative','meditative','reflective','broody','pensive','pondering','wistful']
,['aggression','aggressive']
,['angst','anxiety','anxious','jumpy','nervous','angsty']
,['confident','encouraging','encouragement','optimism','optimistic']
,['desire','hope','hopeful','mood: hopeful']
,['earnest','heartfelt']
,['pessimism','cynical','pessimistic','weltschmerz','cynical/sarcastic']
,['excitement','exciting','exhilarating','thrill','ardour','stimulating','thrilling','titillating']]